name: Docker Image and Deploy

on:
  push:
    branches: ["main"]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ShrekIT
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: lswarss/shrekit
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: lswarss/shrekit:apip-image
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: monkfish-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed."
